# Generated by Django 3.2.2 on 2021-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepics/default.png', upload_to='profilepics'),
        ),
    ]
