# Generated by Django 3.2.2 on 2021-05-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
