# Generated by Django 4.0.1 on 2022-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30, unique=True)),
                ('p_image', models.ImageField(default='productpics/default.png', upload_to='productpics')),
                ('p_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'kids')], max_length=100)),
                ('p_category', models.CharField(choices=[('men', (('Sherwani', 'Sherwani'), ('Tshirts', 'Tshirts'), ('Formals', 'Formals'))), ('women', (('Kurtis', 'Kurtis'), ('Sarees', 'Sarees'), ('Lehangachouli', 'Lehangachouli'))), ('kid', (('Traditional', 'Traditional'), ('Tshirts', 'Tshirts'), ('OneSies', 'OneSies')))], max_length=100)),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_description', models.TextField()),
            ],
        ),
    ]
