# Generated by Django 4.0.1 on 2022-04-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.CharField(choices=[('men', (('Sherwani', 'Sherwani'), ('Tshirts', 'Tshirts'), ('Formals', 'Formals'))), ('women', (('Kurtas', 'Kurtas'), ('Sarees', 'Sarees'), ('Lehangachouli', 'Lehangachouli'))), ('kid', (('Traditional', 'Traditional'), ('Tshirts', 'Tshirts'), ('OneSies', 'OneSies')))], max_length=100),
        ),
    ]
