# Generated by Django 3.2.2 on 2021-05-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_p_name'),
        ('payment', '0004_card_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
