# Generated by Django 3.2.2 on 2021-05-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_card_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(),
        ),
    ]
