# Generated by Django 3.2.2 on 2021-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_image', models.ImageField(default='productpics/default.png', upload_to='productpics')),
                ('p_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'kids')], max_length=100)),
                ('p_category', models.CharField(choices=[('men', (('Sherwani', 'Sherwani'), ('Tshirts', 'Tshirts'), ('Formals', 'Formals'))), ('women', (('Kurtis', 'Kurtis'), ('Sarees', 'Sarees'), ('Lehangachouli', 'Lehangachouli')))], max_length=100)),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_description', models.TextField()),
            ],
        ),
    ]
