# Generated by Django 4.0.1 on 2022-04-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_product'),
        ('productcart', '0002_alter_cart_product'),
        ('home', '0007_alter_product_p_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
