# Generated by Django 3.2.2 on 2021-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_shipping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
