# Generated by Django 3.2.2 on 2021-05-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
