# Generated by Django 3.2.2 on 2021-05-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='size',
        ),
    ]
